// 더미 데이터 - Supabase 연결 전 UI 개발용

export const MOCK_SPORTS = [
  { id: 's1', code: 'running', name: '러닝', category: 'outdoor', emoji: '🏃' },
  { id: 's2', code: 'cycling', name: '자전거', category: 'outdoor', emoji: '🚴' },
  { id: 's3', code: 'fitness', name: '헬스', category: 'indoor', emoji: '💪' },
  { id: 's4', code: 'soccer', name: '축구', category: 'team', emoji: '⚽' },
  { id: 's5', code: 'basketball', name: '농구', category: 'team', emoji: '🏀' },
  { id: 's6', code: 'tennis', name: '테니스', category: 'racket', emoji: '🎾' },
  { id: 's7', code: 'badminton', name: '배드민턴', category: 'racket', emoji: '🏸' },
  { id: 's8', code: 'swimming', name: '수영', category: 'indoor', emoji: '🏊' },
  { id: 's9', code: 'hiking', name: '등산', category: 'outdoor', emoji: '🧗' },
  { id: 's10', code: 'yoga', name: '요가', category: 'indoor', emoji: '🧘' },
]

export const MOCK_PROFILES = [
  {
    id: 'u1',
    nickname: '러닝메이트김',
    avatar_url: null,
    exercise_level: 'intermediate',
    trust_score: 87,
    preferred_sports: ['s1', 's9'],
    workout_traits: ['규칙적', '조용한 편'],
    activity_area: '마포구',
  },
  {
    id: 'u2',
    nickname: '헬스왕박',
    avatar_url: null,
    exercise_level: 'advanced',
    trust_score: 92,
    preferred_sports: ['s3', 's4'],
    workout_traits: ['열정적', '초보환영'],
    activity_area: '강남구',
  },
  {
    id: 'u3',
    nickname: '새벽자전거이',
    avatar_url: null,
    exercise_level: 'beginner',
    trust_score: 74,
    preferred_sports: ['s2'],
    workout_traits: ['조용한 편'],
    activity_area: '용산구',
  },
]

export const MOCK_SPARKS = [
  {
    id: 'spark1',
    host_id: 'u2',
    host: MOCK_PROFILES[1],
    sport_id: 's1',
    sport: MOCK_SPORTS[0],
    title: '한강 러닝 같이 뛰어요 🏃',
    description: '새벽 한강 러닝 함께할 분 구해요! 페이스는 km당 6분대로 가볍게 달릴 예정이에요. 초보도 환영합니다!',
    place_name: '여의도 한강공원',
    address: '서울 영등포구 여의동로 330',
    latitude: 37.5283,
    longitude: 126.9342,
    scheduled_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 60,
    capacity: 4,
    min_level: 'beginner',
    max_level: 'intermediate',
    gender_condition: 'any',
    status: 'recruiting',
    participants: [{ count: 2 }],
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spark2',
    host_id: 'u1',
    host: MOCK_PROFILES[0],
    sport_id: 's3',
    sport: MOCK_SPORTS[2],
    title: '강남 헬스장 파트너 모집',
    description: '강남역 근처 헬스장에서 같이 운동할 분 찾아요. 웨이트 위주로 할 예정입니다.',
    place_name: '강남역 피트니스센터',
    address: '서울 강남구 강남대로 지하 396',
    latitude: 37.4979,
    longitude: 127.0276,
    scheduled_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 90,
    capacity: 2,
    min_level: 'intermediate',
    max_level: null,
    gender_condition: 'any',
    status: 'recruiting',
    participants: [{ count: 1 }],
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spark3',
    host_id: 'u3',
    host: MOCK_PROFILES[2],
    sport_id: 's6',
    sport: MOCK_SPORTS[5],
    title: '주말 테니스 복식 모집!',
    description: '테니스 복식 4명 채우기! 실력 무관 즐기면서 하는 분들 환영해요.',
    place_name: '올림픽공원 테니스장',
    address: '서울 송파구 올림픽로 424',
    latitude: 37.5198,
    longitude: 127.1219,
    scheduled_at: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 120,
    capacity: 4,
    min_level: 'beginner',
    max_level: 'advanced',
    gender_condition: 'any',
    status: 'recruiting',
    participants: [{ count: 3 }],
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spark4',
    host_id: 'u2',
    host: MOCK_PROFILES[1],
    sport_id: 's7',
    sport: MOCK_SPORTS[6],
    title: '배드민턴 초보 환영 🏸',
    description: '배드민턴 배우고 싶은 분 같이 해요! 초보도 천천히 알려드릴게요.',
    place_name: '망원 배드민턴장',
    address: '서울 마포구 망원동 458-1',
    latitude: 37.5556,
    longitude: 126.9013,
    scheduled_at: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 90,
    capacity: 6,
    min_level: 'beginner',
    max_level: null,
    gender_condition: 'any',
    status: 'recruiting',
    participants: [{ count: 4 }],
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'spark5',
    host_id: 'u1',
    host: MOCK_PROFILES[0],
    sport_id: 's2',
    sport: MOCK_SPORTS[1],
    title: '북악산 자전거 라이딩',
    description: '북악산 코스 라이딩! 중급 이상 참여 가능합니다.',
    place_name: '북악산 자전거 출발점',
    address: '서울 종로구 자하문로5가길 1',
    latitude: 37.5903,
    longitude: 126.9688,
    scheduled_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 180,
    capacity: 8,
    min_level: 'intermediate',
    max_level: null,
    gender_condition: 'any',
    status: 'recruiting',
    participants: [{ count: 5 }],
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_EXERCISE_SESSIONS = [
  {
    id: 'ex1',
    user_id: 'u1',
    sport_id: 's1',
    sport: MOCK_SPORTS[0],
    mode: 'solo',
    title: '아침 러닝',
    started_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    ended_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    duration_seconds: 2700,
    distance_meters: 5200,
    calories: 320,
    status: 'completed',
  },
  {
    id: 'ex2',
    user_id: 'u1',
    sport_id: 's3',
    sport: MOCK_SPORTS[2],
    mode: 'solo',
    title: '헬스 웨이트',
    started_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    ended_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
    duration_seconds: 3600,
    distance_meters: null,
    calories: 450,
    status: 'completed',
  },
  {
    id: 'ex3',
    user_id: 'u1',
    sport_id: 's1',
    sport: MOCK_SPORTS[0],
    mode: 'spark',
    title: '한강 러닝 번개',
    started_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    ended_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 50 * 60 * 1000).toISOString(),
    duration_seconds: 3000,
    distance_meters: 8100,
    calories: 480,
    status: 'completed',
  },
]

export const MOCK_CHALLENGES = [
  {
    id: 'c1',
    title: '30일 러닝 챌린지',
    description: '30일 동안 매일 러닝 기록을 남겨보세요!',
    challenge_type: 'exercise',
    goal_count: 30,
    reward_xp: 500,
    starts_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    emoji: '🏆',
    progress: { current_count: 12, completed_at: null, reward_claimed: false },
  },
  {
    id: 'c2',
    title: '주 4회 운동하기',
    description: '이번 주 4번 이상 운동 기록을 채워보세요.',
    challenge_type: 'exercise',
    goal_count: 4,
    reward_xp: 75,
    starts_at: new Date().toISOString(),
    ends_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    emoji: '🏆',
    progress: { current_count: 3, completed_at: null, reward_claimed: false },
  },
  {
    id: 'c3',
    title: '무운대탐',
    description: '새로운 운동 종목 3가지를 도전해보세요.',
    challenge_type: 'exercise',
    goal_count: 3,
    reward_xp: 100,
    starts_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    emoji: '🏆',
    progress: { current_count: 3, completed_at: new Date().toISOString(), reward_claimed: true },
  },
  {
    id: 'c4',
    title: '번개 3회 오픈해보기',
    description: '직접 번개 모임을 3번 만들어보세요.',
    challenge_type: 'spark',
    goal_count: 3,
    reward_xp: 150,
    starts_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    emoji: '🏆',
    progress: { current_count: 1, completed_at: null, reward_claimed: false },
  },
  {
    id: 'c5',
    title: '어제의 나 이기기',
    description: '지난 주보다 더 많은 운동 거리를 기록해보세요.',
    challenge_type: 'exercise',
    goal_count: 1,
    reward_xp: 50,
    starts_at: new Date().toISOString(),
    ends_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    emoji: '🏆',
    progress: { current_count: 1, completed_at: new Date().toISOString(), reward_claimed: false },
  },
  {
    id: 'c6',
    title: '5km 한강 달리고 오!소리 나게 선물 받자',
    description: '한강에서 5km 러닝 완주 후 인증샷을 올려보세요. 추첨을 통해 선물을 드립니다!',
    challenge_type: 'event',
    goal_count: 1,
    reward_xp: 300,
    starts_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    emoji: '🎁',
    event_rewards: [
      { rank: '1등 선물 (3명)', desc: '신세계 상품권 5만원' },
      { rank: '2등 선물 (10명)', desc: '참여자 전원 앱 내 경험치 5배 지급' },
    ],
    event_date: '2026. 7. 00',
    event_place: '반포한강공원 달빛광장',
    progress: null,
  },
]

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    type: 'spark_approved',
    title: '번개 참여 승인!',
    body: '한강 러닝 같이 뛰어요 번개에 참여가 승인됐어요.',
    read_at: null,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'n2',
    type: 'spark_new_join',
    title: '새로운 참여 신청',
    body: '러닝메이트김 님이 번개 참여를 신청했어요.',
    read_at: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n3',
    type: 'challenge_complete',
    title: '챌린지 완료!',
    body: '무운대탐 챌린지를 완료했어요. +100 XP',
    read_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n4',
    type: 'spark_reminder',
    title: '오늘 번개가 있어요!',
    body: '오늘 20:00 한강 러닝 번개가 곧 시작돼요.',
    read_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n5',
    type: 'spark_review',
    title: '후기를 남겨주세요',
    body: '참여한 번개가 종료됐어요. 함께한 분들에게 후기를 남겨주세요.',
    read_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_USER_PROFILE = {
  id: 'current-user',
  nickname: '나는야러너',
  avatar_url: null,
  gender: null,
  birth_year: 1995,
  exercise_level: 'intermediate',
  trust_score: 82,
  preferred_sports: ['s1', 's3', 's9'],
  workout_traits: ['꾸준함', '새벽형'],
  activity_area: '마포구',
  weekly_count: 3,
  xp: 1240,
}

export const SPORT_EMOJI: Record<string, string> = {
  running: '🏃',
  cycling: '🚴',
  fitness: '💪',
  soccer: '⚽',
  basketball: '🏀',
  tennis: '🎾',
  badminton: '🏸',
  swimming: '🏊',
  hiking: '🧗',
  yoga: '🧘',
  walking: '🚶',
  racket_sports: '🏸',
}
